<a href="https://colab.research.google.com/github/loveshersingh12/AI-Virtual-Painter/blob/Python_for_AI_and_ML/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some  of the most fundatmentals concepts of tensors using TensorFlow

More specifically, we're going to cover:


*   Introduction to tensors
*   Getting information from tensors
*   Manipulating tensors
*   Tensors & Numpy
*   Using @tf.function (a way to speed up regular Python functions)
*   Using GPUs with TensorFlow (or TPUs)
*   Exercises








## Introductions to Tensors

In [ ]:
# import TensorFlow
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.18.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndm stands from number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 0])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  0], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                    [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create anothr matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the data type with dtype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# What's the number of dimensions of another matrix
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# What we've create so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimension array of numbers
*Tensors: An n-dimensional array of numbers(when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

# Creating tensors with tf.Variable

In [ ]:
# Create the sane tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change onr of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))


# Are they equal?
random_1, random_2, random_1 == random_2

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)

not_shuffled = tf.constant([[10, 7, 3],
                            [3, 4, 5],
                            [2, 5, 8]])

# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 3,  4,  5],
       [ 2,  5,  8],
       [10,  7,  3]], dtype=int32)>

In [ ]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7,  3],
       [ 3,  4,  5],
       [ 2,  5,  8]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7,  3],
       [ 2,  5,  8],
       [ 3,  4,  5]], dtype=int32)>

### Other ways to create tensors

In [ ]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turn NumPy arrays into tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensords can be run on a GPU computing (much faster for American computing)

In [ ]:
# You can also tyrn NumPy arrays into tensors


numpy_A = np.arange(1, 25, dtype=np.int32) # create a Numpy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=[6, 4])
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
A.ndim

2

### Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimenisons (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimenisons (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :4, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                           [3, 4]])

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimenion to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # -1 means expand the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic Operations**

+,-,*,/

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Subraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

** Matrix Multipllication**

In machine learning, matrix multiplication is one of the most common tensor operations.

In [ ]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operator "@"
A = tf.constant([[1,2,5],
                 [7,2,1],
                 [3,3,3]])
B = tf.constant([[3,5],
                 [6,7],
                  [1,8]])

In [ ]:
tf.matmul(A, B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

Y = tf.constant([[7,8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
X.shape, tf.reshape(Y, shape=(2, 3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
# Try the multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# Can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matrix multiplicatio between X and Y
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.tensordot(X, tf.transpose)

In [ ]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n")

print("Y reshaped to (2,3):")
print(tf.reshape(Y, (2,3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


## Changing the datatype of a tensor

In [ ]:
# Create a new tensor with default datatyype (float32)
B = tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [ ]:
c = tf.constant([7, 19])
c, c.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 19], dtype=int32)>,
 tf.int32)

In [ ]:
# Change from float32 to float16 (reduce precision)
D = tf.cast(B, dtype = tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
E = tf.cast(c, dtype = tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 19.], dtype=float32)>,
 tf.float32)

In [ ]:
E_float16 = tf.cast(E, dtype= tf.float16)
E_float16, E_float16.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 19.], dtype=float16)>,
 tf.float16)

### Aggragating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values
D = tf.constant([-7, -10] )
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

# Let's go through the follwoing forms of aggregation:


* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor





In [ ]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([75, 96,  8, 55, 23, 58,  5, 54, 10, 75, 28, 13,  1, 84, 78,  0, 38,
       82, 52, 73, 77, 78, 54, 62, 30, 80, 80, 21, 27, 91, 43, 12, 34, 65,
       22, 77, 99, 59, 47, 72, 82, 93, 72, 49, 81, 79, 86, 39, 60, 47])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# minimum of numbers
a = tf.math.minimum(D, c)
# Test with tensors
b = tf.math.maximum(D, c)
a, b

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 19], dtype=int32)>)

In [ ]:
# Using reduce_mean
tf.reduce_min(E), tf.reduce_max(E), tf.reduce_mean(E), tf.reduce_sum(E)


(<tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=97>,
 <tf.Tensor: shape=(), dtype=int64, numpy=52>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2630>)

In [ ]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([43, 30, 53, 35, 21, 81, 76, 27, 76,  6, 79, 22, 84, 97, 27, 68, 60,
       30, 30, 56, 85, 94, 22, 42, 45, 17, 52, 94, 43, 86, 79, 96, 48, 91,
       12, 62, 88, 25, 18, 79, 95,  3, 31, 43, 78,  0, 19, 78, 14, 90])>

In [ ]:
# Variance and standard deviation

tf.math.reduce_variance(tf.cast(E, dtype=tf.float32)), tf.math.reduce_std(tf.cast(E, dtype=tf.float32))


(<tf.Tensor: shape=(), dtype=float32, numpy=877.6799926757812>,
 <tf.Tensor: shape=(), dtype=float32, numpy=29.62566375732422>)

In [ ]:
# Another Variance and standard deviation
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=780>

In [ ]:
tfp.stats.stddev(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.940824508666992>

### Find the positional maximum and minimum

In [ ]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([75, 96,  8, 55, 23, 58,  5, 54, 10, 75, 28, 13,  1, 84, 78,  0, 38,
       82, 52, 73, 77, 78, 54, 62, 30, 80, 80, 21, 27, 91, 43, 12, 34, 65,
       22, 77, 99, 59, 47, 72, 82, 93, 72, 49, 81, 79, 86, 39, 60, 47])>

In [ ]:
tf.argmin(E), tf.argmax(E), tf.a

(<tf.Tensor: shape=(), dtype=int64, numpy=15>,
 <tf.Tensor: shape=(), dtype=int64, numpy=36>)

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(50)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.94196117, 0.1697309 , 0.5064962 , 0.27598453, 0.899318  ,
       0.4486513 , 0.43584716, 0.71771336, 0.85751176, 0.12559032,
       0.0875535 , 0.85261035, 0.17349517, 0.31913245, 0.4845121 ,
       0.5540675 , 0.6620537 , 0.20845115, 0.43225408, 0.9061552 ,
       0.52628434, 0.30039036, 0.5774927 , 0.5814352 , 0.7920803 ,
       0.396855  , 0.02649951, 0.43159127, 0.11073196, 0.5804652 ,
       0.83437836, 0.17531359, 0.5109179 , 0.91586626, 0.21497321,
       0.41104853, 0.7946409 , 0.30716085, 0.3172475 , 0.15829349,
       0.5417241 , 0.49205697, 0.19820452, 0.25472498, 0.2333138 ,
       0.2071842 , 0.5443722 , 0.01052618, 0.57121956, 0.33880603],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9419611692428589>

In [ ]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9419611692428589>

In [ ]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
#  Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [ ]:
#  find the minimum using the positional index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.010526180267333984>

### Squeezing a tensor (Removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(50)
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.94196117, 0.1697309 , 0.5064962 , 0.27598453, 0.899318  ,
           0.4486513 , 0.43584716, 0.71771336, 0.85751176, 0.12559032,
           0.0875535 , 0.85261035, 0.17349517, 0.31913245, 0.4845121 ,
           0.5540675 , 0.6620537 , 0.20845115, 0.43225408, 0.9061552 ,
           0.52628434, 0.30039036, 0.5774927 , 0.5814352 , 0.7920803 ,
           0.396855  , 0.02649951, 0.43159127, 0.11073196, 0.5804652 ,
           0.83437836, 0.17531359, 0.5109179 , 0.91586626, 0.21497321,
           0.41104853, 0.7946409 , 0.30716085, 0.3172475 , 0.15829349,
           0.5417241 , 0.49205697, 0.19820452, 0.25472498, 0.2333138 ,
           0.2071842 , 0.5443722 , 0.01052618, 0.57121956, 0.33880603]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.94196117, 0.1697309 , 0.5064962 , 0.27598453, 0.899318  ,
        0.4486513 , 0.43584716, 0.71771336, 0.85751176, 0.12559032,
        0.0875535 , 0.85261035, 0.17349517, 0.31913245, 0.4845121 ,
        0.5540675 , 0.6620537 , 0.20845115, 0.43225408, 0.9061552 ,
        0.52628434, 0.30039036, 0.5774927 , 0.5814352 , 0.7920803 ,
        0.396855  , 0.02649951, 0.43159127, 0.11073196, 0.5804652 ,
        0.83437836, 0.17531359, 0.5109179 , 0.91586626, 0.21497321,
        0.41104853, 0.7946409 , 0.30716085, 0.3172475 , 0.15829349,
        0.5417241 , 0.49205697, 0.19820452, 0.25472498, 0.2333138 ,
        0.2071842 , 0.5443722 , 0.01052618, 0.57121956, 0.33880603],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3, 2] # could be red, green, blue, purple

# one hot encode our list of indices
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth = 4, on_value="ones",  off_value="zeros")

<tf.Tensor: shape=(5, 4), dtype=string, numpy=
array([[b'ones', b'zeros', b'zeros', b'zeros'],
       [b'zeros', b'ones', b'zeros', b'zeros'],
       [b'zeros', b'zeros', b'ones', b'zeros'],
       [b'zeros', b'zeros', b'zeros', b'ones'],
       [b'zeros', b'zeros', b'ones', b'zeros']], dtype=object)>

### Squaring, log, square root

In [ ]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the squareroot
tf.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and numpy

TensorFlow interacts beautifully with NumPy arrays.

Note: One of the main differences between a TensorFlow tensor and a NumPy array is a TensorFlow can be run on a GPU or a TPU (for faster processing)

In [ ]:
# Create a tensor directly from a numpy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Convert tenosr J to a Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# The default of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sat Mar 29 06:57:00 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   59C    P8             10W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

🔑**Note**: If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.

# Exercise

### 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [ ]:
vec = tf.constant([1, 2])
sca = tf.constant(5)
matrix = tf.constant([[1, 2], [3, 5]])
tensor = tf.constant([[15, 25], [35, 55]])
vec, sca, matrix, tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[15, 25],
        [35, 55]], dtype=int32)>)

### 2. Find the shape, rank and size of the tensors you created in 1.

In [ ]:

vec.shape, sca.shape, matrix.shape, tensor.shape


(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
vec.ndim, sca.ndim, matrix.ndim, tensor.ndim

(1, 0, 2, 2)

In [ ]:
tf.size(vec), tf.size(sca), tf.size(matrix), tf.size(tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

### 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [ ]:
zer = tf.zeros(shape = [5, 300])
one = tf.ones(shape=[5, 300])
zer, one

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)>)

### 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
tf.matmul(zer, tf.transpose(one))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.tensordot(zer, tf.transpose(one), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### 4.Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [ ]:
x = tf.random.uniform(shape=[224, 224, 3])
x

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.37688518, 0.66926944, 0.80108917],
        [0.18081868, 0.42665863, 0.77253556],
        [0.8921802 , 0.76322126, 0.31330812],
        ...,
        [0.24146414, 0.26272595, 0.9893695 ],
        [0.07333755, 0.21327972, 0.9020307 ],
        [0.31755924, 0.00181031, 0.32140446]],

       [[0.07508028, 0.5266353 , 0.4534117 ],
        [0.5057299 , 0.7795577 , 0.18559372],
        [0.23496425, 0.07078588, 0.35522282],
        ...,
        [0.312912  , 0.93908024, 0.36316645],
        [0.8129896 , 0.26123035, 0.34763634],
        [0.570588  , 0.7597282 , 0.7185999 ]],

       [[0.5853634 , 0.09268486, 0.72279775],
        [0.00995767, 0.4025439 , 0.5824338 ],
        [0.89803386, 0.35713375, 0.22994661],
        ...,
        [0.8038287 , 0.4807998 , 0.57448626],
        [0.4986539 , 0.6738348 , 0.36035526],
        [0.54286814, 0.18638468, 0.5405829 ]],

       ...,

       [[0.25838745, 0.54011846, 0.6569767 ],
        [0.33

### 7. Find the min and max values of the tensor you created in 6 along the first axis.

In [ ]:
tf.reduce_max(x, 1), tf.reduce_min(x, 1)

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[0.9998405 , 0.9912616 , 0.9893695 ],
        [0.9978031 , 0.98633265, 0.98539865],
        [0.9970982 , 0.99612284, 0.9959717 ],
        [0.99549425, 0.9965658 , 0.9950888 ],
        [0.99515593, 0.99908817, 0.98883736],
        [0.999261  , 0.99839294, 0.9981586 ],
        [0.99757135, 0.99689245, 0.99938536],
        [0.9970335 , 0.99993753, 0.9990883 ],
        [0.9958581 , 0.99453676, 0.993001  ],
        [0.9975966 , 0.9980782 , 0.99486303],
        [0.99649215, 0.996819  , 0.9983183 ],
        [0.9913734 , 0.99636495, 0.9908378 ],
        [0.99601114, 0.99823916, 0.994557  ],
        [0.99841666, 0.99465454, 0.994601  ],
        [0.99241996, 0.99221873, 0.9976182 ],
        [0.9889425 , 0.9992751 , 0.99637926],
        [0.9937403 , 0.999954  , 0.99736786],
        [0.99887776, 0.9981179 , 0.99860585],
        [0.997808  , 0.9892967 , 0.99778104],
        [0.9982816 , 0.9993479 , 0.99956656],
        [0.99885917, 0.994708

### 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [ ]:
y = tf.random.uniform(shape=([1, 224, 224, 3]))
y_squeezed = tf.squeeze(y)
y, y_squeezed

(<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
 array([[[[0.9346715 , 0.9685786 , 0.39447176],
          [0.12713742, 0.7493472 , 0.08963108],
          [0.5428119 , 0.20059848, 0.8653251 ],
          ...,
          [0.6212708 , 0.36430728, 0.5167892 ],
          [0.29467595, 0.28256834, 0.63840437],
          [0.24208772, 0.25354898, 0.3611666 ]],
 
         [[0.837988  , 0.5089283 , 0.98544884],
          [0.17408633, 0.30686176, 0.76076853],
          [0.85747695, 0.00367773, 0.23806381],
          ...,
          [0.363559  , 0.33778548, 0.4154241 ],
          [0.0383718 , 0.12745762, 0.5993918 ],
          [0.27478778, 0.28029776, 0.8986225 ]],
 
         [[0.2796477 , 0.6767318 , 0.72122693],
          [0.5227587 , 0.4605503 , 0.4059832 ],
          [0.26402926, 0.96623504, 0.6300652 ],
          ...,
          [0.6880717 , 0.6301794 , 0.3739767 ],
          [0.03671408, 0.794031  , 0.00740612],
          [0.1200763 , 0.8690618 , 0.9693831 ]],
 
         ...,
 
       

### 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [ ]:
z = tf.range(1, 11)
z, tf.argmax(z)

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int64, numpy=9>)

### 10. One-hot encode the tensor you created in 9.

In [ ]:
tf.one_hot(z, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>